### ISSUE TITLE
separazione lcm1/lcm2/laur, handling multipli selector `-1 -m`, output di `whoall -m`

### ISSUE THREAD

**Issue by eguiraud** [lcm-unimi/whoall#2]
We,
vedo due problemi con il codice attuale che sono abbastanza intrecciati da meritare una sola issue.
- l'inserimento nell'output dei separatori LCM1, LCM2, LAUR viene fatta nel momento in cui lo script stampa determinati nomi di nodi. e.g. appena prima di stampare 'abe' viene stampato 'LCM1', appena prima di stampare 'actarus' viene stampato 'LCM2', ecc. Questo meccanismo è la cosa piu' prona ad errori che si potesse fare:
  - se l'ordine dei nomi dei nodi viene cambiato si sputtana tutto
  - se per qualche motivo non stampo piu' 'abe' (per esempio perchè non ha condor e ho chiesto di stampare solo i nodi condor) non viene piu' stampato nemmeno 'LCM'
  - se l'ordine in cui stampo i nodi non è { nodiLCM1, nodiLCM2 } l'output si sputtana **questo è il motivo per cui l'output di `whoall -m` è sputtanato**)
- non è affatto chiaro quale debba essere il comportamento dello script nel momento in cui eseguo `whoall -m -1`. devo stampare solo i nodi di LCM1? solo i nodi con mathematica? o solo i nodi di LCM1 con mathematica?

**Proposta di soluzione:**
Aggiungiamo alla classe `Node`, che si occupa di comporre la lista degli utenti connessi per ogni nodo, degli attributi che descrivono il nodo. Oltre che `self.hostname` aggiungerei `self.location` (LCM1, LCM2, LAUR), `self.mathematica` (M4, M5, None), `self.condor` (True, False).
1. all'inizio dello script creiamo un dizionario con tutti i nodi di LCM e i loro attributi (così la lista di nodi diventa facilmente editabile e si possono aggiungere/togliere attributi a piacere)
2. costruiamo i vari `Node` a partire da quel dizionario
3. per ogni `Node` eseguiamo il metodo che controlla gli utenti connessi (in parallelo, com'è adesso)
4. usiamo `filter` per prendere dalla lista dei `Node` i sottoinsiemi che ci interessano. Secondo me la cosa giusta è che se chiedo `-1 -m` vengono stampati solo i nodi di LCM1 con mathematica.

I cambiamenti al codice già esistente dovrebbero coinvolgere solamente la definizione delle liste dei nodi (che diventa un dizionario, quindi piu' elastico e intuitivo da modificare, e non richiede piu' che i nodi siano messi in un certo ordine), l'aggiunta a `Node` di qualche attributo, e il ciclo che stampa i nodi con i loro utenti (che viene modificato per filtrare i nodi da stampare a seconda delle opzioni).

Che dite? Consigli/commenti/pesanti critiche?

**Comment by eguiraud** [comment]
non so se vi arrivano le notifiche per le issue create così, quindi vi evoco: @lcm-unimi/lcm-dev xD

**Comment by algebrato** [comment]
Sì sì arrivano. In più se hai l'app sul telefono di guthub puoi anche rispondere al volo

**Comment by andreatsh** [comment]
Se ho capito bene tu proponi di:
1. eseguire il metodo di controllo per ogni `Node` del cluster
2. filtrare e stampare solo le info sui nodi richiesti

Io personalmente troverei piu' sensato:
1.  filtrare i nodi richiesti
2.  usare il metodo di controllo di `Node` solo su quei nodi
3.  stampare a video le info 

Per il resto mi sembra una buona proposta!

**Comment by eguiraud** [comment]
Sì hai ragione mi sono messo a giocare un po' con il codice e ovviamente ho fatto come dici tu. In pratica i punti 3 e 4 sono invertiti rispetto a come li ho scritti.
