### ISSUE TITLE
Annoying asymmetry in output

### ISSUE THREAD

**Issue by Sbozzolo** [lcm-unimi/whoall#6]
Whoall's output has a major asymmetry, namely, the third line is something like:
`Done... ( 1.135 s)`
While it should be:
`Done... (1.135 s)`
Or:
`Done... ( 1.135 s )`
This glitch is easily fixed by acting on [this line](https://github.com/lcm-unimi/whoall/blob/master/whoall#L359).

**Comment by eguiraud** [comment]
open a PR?

**Comment by Sbozzolo** [comment]
Since there are four people who have to edit this file to add their name among the admins, I'd prefer them to fix this issue while performing that task.  This will prevent me from opening a new branch and open a PR just to add a space.

**Comment by eguiraud** [comment]
fair enough. just so you know, for small stuff like this you can edit the file and open a PR directly from github
